title: Serve dois
description: Receitas que dão certo
theme: jekyll-theme-cayman
url: https://servedois.github.io
google_analytics: UA-175048829-1

# staticman comments configuration
staticman_url: https://servedois-staticman.herokuapp.com/v2/entry/servedois/servedois.github.io/master/comments
reCaptcha:
  siteKey: 6LcizL4ZAAAAAEkfn3z85oaf22kXKWtClkzOwO60
    # the secret is the encrypted blob you got back from the encrypt call
  secret: HWpSk0nsfLMnAUzL16et3qVEq+BF3aqgUEebmijN3we9N0nW1AtKBezUvC1Ie/M+eUx5OwLkyryO6L7r8rWF/6COdEPrF0AGUcaXMmT+ruihUDArkJEgrS96XRagZ1I1q+Xjhbbec6NUF7OuYaJqozdortPF6jTFDd+LT6qUoWmnOex7zdN8Y+xjwVUPkc42eHzse3C5KpnZ6ZZsz6a6lKX7W8tO5EyHDUVpWcFOw5kfHUPMXGMjvay0eUyGUFWM2bk6pN/uKrFkQQehE6beyZDOKf1M7pbD6wGJE/vofl/N1TW4P55YzhKvN+BnvwGTPn7fshT4MsTN+lC1hBguyT9Os7ZuP3uC+KCe72v6JwbyU6V6+BdBGbqg2xnahnJUOJnmyFj194Ozu84g+mjHi8eK3Jbipn8kPgicrzVm22kgnHxs4rShpXbRyo3dWyxpUqOO263aKKdEzexBGohKDebBTw2QAu2HC8VidnQE5zOlo0RdH4MpNXzN83KvoVifyR2DHV1y2wOpfJZCoXINJXSEykMqcctky0Yt9Zq7qfWvESv5rFXIISJryg6Gc8rGIAhsmCG7nl2cgvJ/edxC0ttxYHbdxJW8W9OE6yGNAhxr5oZU2kHSf4GdhHm6Slfgp42aE+sII2S/ZTOCUoKe6+UBHPeMzEe5UOZI9troYQs=
